run-time error gives insight into traits and child classes:
[info] Running fpinscala.monads.MonadTest
[error] (run-main-12) scala.NotImplementedError: an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at fpinscala.monads.Monad$.<init>(Monad.scala:496)
	at fpinscala.monads.Monad$.<clinit>(Monad.scala)
	at fpinscala.monads.MonadTest$.main(Monad.scala:564)
	at fpinscala.monads.MonadTest.main(Monad.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run 'last exercises/compile:run' for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run 'last exercises/compile:run' for the full output.
[error] (exercises/compile:run) Nonzero exit code: 1
[error] Total time: 2 s, completed May 2, 2015 12:02:48 PM