implemented Gen's listOfN method with Gen's Monad instance. About to debug MonadB and MonadC traits. Compiler errors given currently are illustrative of the rules of traits. Where is "override" required?  What does "final" mean?  Do these errors indicate that the FP in Scala book already had the best possible implementation for three primitive sets of monad methods?
[error] /Users/peterbecich/scala/fpinscala/exercises/src/main/scala/fpinscala/monads/Monad.scala:195: method map overrides nothing.
[error] Note: the super classes of trait listFunctorAlt contain the following, non final members named map:
[error] def map[A, B](fa: List[A])(f: A => B): List[B]
[error]     override def map[B](as: List[A])(f: A => B): List[B] = as map f
[error]                  ^
[error] /Users/peterbecich/scala/fpinscala/exercises/src/main/scala/fpinscala/monads/Monad.scala:301: object creation impossible, since:
[error] it has 2 unimplemented members.
[error] /** As seen from <$anon: fpinscala.monads.Mon[Option]>, the missing signatures are as follows.
[error]  *  For convenience, these are usable as stub implementations.
[error]  */
[error]   def flatMap[A, B](fa: Option[A])(f: A => Option[B]): Option[B] = ???
[error]   def unit[A](a: => A): Option[A] = ???
[error]   def monOptionAsDef[A] = new Mon[Option]{
[error]                               ^
[error] /Users/peterbecich/scala/fpinscala/exercises/src/main/scala/fpinscala/monads/Monad.scala:524: overriding method map2 in trait Monad of type [A, B, C](ma: M[A], mb: M[B])(f: (A, B) => C)M[C];
[error]  method map2 needs `override' modifier
[error]   def map2[A,B,C](ma: M[A], mb: M[B])(f: (A, B) => C): M[C] =
[error]       ^
[warn] 72 warnings found
[error] three errors found
[error] (exercises/compile:compile) Compilation failed
[error] Total time: 3 s, completed May 1, 2015 11:17:25 AM